### ISSUE TITLE
Module packaging has no attribute version

### ISSUE THREAD

**Issue by astrobatty** [astropy/ccdproc#786]
The `cosmicray_lacosmic` function tries to check the version of `astroscrappy` by using `packaging`. However, the `packaging` somehow does not support version checking if the `version` module is not imported itself.

Here is an example how to reproduce the error:
```python
import numpy as np
from ccdproc import  cosmicray_lacosmic

img = np.ones((10,10))

_ = cosmicray_lacosmic(img)
```

The raised error will be:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-93e4d7b2730a> in <module>()
      4 img = np.ones((10,10))
      5 
----> 6 _ = cosmicray_lacosmic(img)

1 frames
/usr/local/lib/python3.7/dist-packages/ccdproc/core.py in cosmicray_lacosmic(ccd, sigclip, sigfrac, objlim, gain, readnoise, satlevel, pssl, niter, sepmed, cleantype, fsmode, psfmodel, psffwhm, psfsize, psfk, psfbeta, verbose, gain_apply, inbkg, invar)
   1519 
   1520     # Handle transition from old astroscrappy interface to new
-> 1521     old_astroscrappy_interface = (packaging.version.parse(asy_version) <
   1522                                   packaging.version.parse('1.1.0'))
   1523 

AttributeError: module 'packaging' has no attribute 'version'
```

According to the `packaging` [documentation](https://packaging.pypa.io/en/latest/version.html), `version` should be used like
```python
from packaging.version import parse

parse('1.1.0')
```
but this also works:
```python
from packaging import version

version.parse('1.1.0')
```

Current versions:
python 3.7.12
packaging 21.3
astropy 4.3.1
ccdproc 2.3.0

**Comment by Yash-10** [comment]
It seems to me it's because of astropy's version. If I try to install the latest stable release of astropy (i.e. `astropy==5.0`), then I do not get any error.

Could you try upgrading `astropy` to `5.0` by `pip install astropy==5.0`, and then try again?

**Comment by astrobatty** [comment]
The problem is not `astropy` itself and I cannot upgrade to `astropy 5.0`, because it is only available for `python>=3.8` and I'm using `3.7`. Nonetheless, I tried your solution in a conda environment and it works. The reason why it works is that `astropy` calls `packaging` like `from packaging import version` before `ccdproc`. Magically, after doing so `packaging` can be used as it is implemented in `ccdproc`.

Here is the previous example, but with `packaging`. This works in `python 3.7`:
```
from packaging import version

import numpy as np
from ccdproc import  cosmicray_lacosmic

img = np.ones((10,10))

_ = cosmicray_lacosmic(img)
```

I suggest to call `packaging` in `ccdproc` as it is done in `astropy` to be able use this code in `python 3.7`. My main reason is that if you want to run/test `ccdproc` in Colab, then you have to use `python 3.7`. Switching to `python>=3.8` is a painful process.

**Comment by Yash-10** [comment]
Thanks, @astrobatty ! It seems a good idea since `3.7` is still supported. Would you like to submit a PR suggesting this change?

**Comment by mwcraig** [comment]
Closed by #787
